export const TOKEN_CONSTANTS = {
  DEFAULT_MAX_OUTPUT_BUDGET: 1000,
  MIN_OUTPUT_BUDGET: 16,
  TOKEN_CONVERSION_RATE: 1,
  TOKEN_USAGE_TYPE_CHAT: "chat" as const,
  DEFAULT_FREE_ALLOCATION: 10000,
  PRO_ALLOCATION: 50000,
  PLUS_ALLOCATION: 100000,
} as const;
